name: iCube

options:
  bundleIdPrefix: com.moonding
  createIntermediateGroups: true
  deploymentTarget:
    iOS: "18.0"

settings:
  base:
    SWIFT_VERSION: "5.0"
    TARGETED_DEVICE_FAMILY: "1"
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    SWIFT_EMIT_LOC_STRINGS: YES
    IPHONEOS_DEPLOYMENT_TARGET: "18.0"
    DEVELOPMENT_TEAM: 75L84BV98K
    CODE_SIGN_STYLE: Automatic

packages:
  CubeKit:
    path: CubeKit
  CubeSolve:
    path: CubeSolve
  CubeScan:
    path: CubeScan

targets:
  iCube:
    type: application
    platform: iOS
    sources:
      - path: iCube
        excludes:
          - "Info.plist"
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moonding.icube
        PRODUCT_NAME: iCube
        INFOPLIST_FILE: iCube/Info.plist
        CURRENT_PROJECT_VERSION: 1
        MARKETING_VERSION: "1.0"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        SUPPORTS_MACCATALYST: NO
    dependencies:
      - package: CubeKit
      - package: CubeSolve
      - package: CubeScan

  iCubeTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: iCubeTests
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.moonding.icube.tests
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: iCube
      - package: CubeKit
      - package: CubeSolve
      - package: CubeScan
